# Project: WEEK09-3
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = week09-3.o
LINKOBJ  = week09-3.o
LIBS     = -L"C:/Users/user/Dev-Cpp/MinGW64/lib" -L"C:/Users/user/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Users/user/Dev-Cpp/MinGW64/include" -I"C:/Users/user/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/user/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Users/user/Dev-Cpp/MinGW64/include" -I"C:/Users/user/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/user/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Users/user/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = WEEK09-3.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

week09-3.o: week09-3.c
	$(CC) -c week09-3.c -o week09-3.o $(CFLAGS)
