# Project: WEEK09-4
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = WEEK09-4.o
LINKOBJ  = WEEK09-4.o
LIBS     = -L"C:/Users/user/Dev-Cpp/MinGW64/lib" -L"C:/Users/user/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Users/user/Dev-Cpp/MinGW64/include" -I"C:/Users/user/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/user/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Users/user/Dev-Cpp/MinGW64/include" -I"C:/Users/user/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/user/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Users/user/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = WEEK09-4.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

WEEK09-4.o: WEEK09-4.c
	$(CC) -c WEEK09-4.c -o WEEK09-4.o $(CFLAGS)
